# 5 Feature

In [91]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('D:/College/Smt 3/Task/Machine Learning/Assignment 8/test.csv')
dataset

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0      0.1        193  ...  16        226      1412  3476    12     7   
1      0.8        191  ...  12        746       857  3895     6     0   
2      0.9        186  ...   4       1270      1366  2396    17    10   
3      0.5         96  ...  20        295      1752  3893    10     0   
4      0.5        108  ...  18        749       810  1773    15     8   
..     ...        ...  ...  ..        ...       ...   ...   ...   ...   
995    0.5        170  ...  17        644       913  2121    14     8   
996    0.9        186  ...   2       1152      1632  1933     8     1   
997    0.5         80  ...  12        477       825  1223     5     0   
998    0.4        171  ...  12         38       832  2509    15    11   
999    0.1        140  ...  19        457       608  2828     9     2   

     talk_time  three_g  touch_screen  wifi  
0            2        0             1     0  
1            7        1             0     0  
2           10        0             1     1  
3            7        1             1     0  
4            7        1             0     1  
..         ...      ...           ...   ...  
995         15        1             1     0  
996         19        0             1     1  
997         14        1             0     0  
998          6        0             1     0  
999          3        1             0     1  

[1000 rows x 21 columns]

In [92]:
data_training = pd.read_csv('D:/College/Smt 3/Task/Machine Learning/Assignment 8/train.csv')
X = data_training.drop(columns='price_range')
Y = data_training["price_range"]


In [93]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_selector = SelectKBest(chi2, k=5) 
chi2_selector.fit(X, Y)

cols = chi2_selector.get_support(indices=True)
data_training = X.iloc[:,cols]
data_training.head()

battery_power  mobile_wt  px_height  px_width   ram
0            842        188         20       756  2549
1           1021        136        905      1988  2631
2            563        145       1263      1716  2603
3            615        131       1216      1786  2769
4           1821        141       1208      1212  1411

In [94]:
from scipy.sparse import data
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(0,1))
train_data = sc.fit_transform(data_training)
print(train_data)

[[0.22778891 0.9        0.01020408 0.17089453 0.61277392]
 [0.34736139 0.46666667 0.46173469 0.99332443 0.63468733]
 [0.04141617 0.54166667 0.64438776 0.811749   0.6272047 ]
 ...
 [0.94188377 0.23333333 0.44285714 0.75567423 0.7485302 ]
 [0.6753507  0.54166667 0.17142857 0.11348465 0.16381614]
 [0.00601202 0.73333333 0.24642857 0.16955941 0.9788883 ]]


In [95]:
dataset = dataset.loc[:,['battery_power','mobile_wt','px_height','px_width','ram']]
dataset

battery_power  mobile_wt  px_height  px_width   ram
0             1043        193        226      1412  3476
1              841        191        746       857  3895
2             1807        186       1270      1366  2396
3             1546         96        295      1752  3893
4             1434        108        749       810  1773
..             ...        ...        ...       ...   ...
995           1700        170        644       913  2121
996            609        186       1152      1632  1933
997           1185         80        477       825  1223
998           1533        171         38       832  2509
999           1270        140        457       608  2828

[1000 rows x 5 columns]

In [96]:
from pandas import test
from scipy.sparse import data
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(0,1))
test_data = sc.fit_transform(dataset)
print(test_data)

[[0.36224149 0.94166667 0.11851075 0.60855043 0.86231884]
 [0.22748499 0.925      0.39119035 0.23780895 0.97477187]
 [0.87191461 0.88333333 0.66596749 0.57782231 0.57246377]
 ...
 [0.45697131 0.         0.2501311  0.21643287 0.25764895]
 [0.68912608 0.75833333 0.01992659 0.22110888 0.6027912 ]
 [0.51367578 0.5        0.23964342 0.07147629 0.6884058 ]]


In [97]:
import pandas as pd
from sklearn.cluster import KMeans

max_iterasi = 10
cluster_i = []
cluster_val = [] 
cluster = []

clustering = KMeans(n_clusters=3, init="random", n_init=1)


for i in range(max_iterasi):
    fit =  clustering.fit(test_data)
    clusters = clustering.predict(test_data)
    sse = clustering.inertia_
    print("\nHasil clustering iterasi ke ",i+1,":\n", clusters)
    print("\nSSE iterasi ke ",i+1,":\n", sse)
    print("------------------------------------------------------")
    cluster_i.append(clusters)
    cluster_val.append(sse)

min_sse = min(cluster_val)

index_min = cluster_val.index(min_sse)

cluster = cluster_i[index_min]





Hasil clustering iterasi ke  1 :
 [1 1 1 1 0 0 1 2 0 0 1 1 2 2 1 2 2 0 1 0 2 1 2 0 1 2 2 0 0 0 1 0 1 0 2 2 1
 0 0 0 2 0 0 0 0 2 0 1 2 0 0 0 1 0 1 0 1 2 0 0 1 0 0 0 2 2 2 1 1 2 0 2 0 1
 1 2 0 2 0 1 0 1 1 2 0 2 0 0 0 2 0 2 0 2 0 2 2 1 2 0 0 2 0 1 0 0 2 2 0 1 1
 1 2 1 1 1 0 2 1 2 2 0 1 0 2 2 1 0 1 2 0 2 2 0 1 2 0 2 1 1 0 0 0 1 0 1 1 0
 1 0 0 1 2 0 1 0 1 0 0 0 2 1 1 1 1 0 2 2 1 0 0 0 1 2 2 1 0 2 0 0 2 0 0 2 0
 1 1 1 2 2 2 2 2 1 2 2 1 2 1 0 0 0 1 1 1 2 1 2 2 0 0 1 0 1 0 1 0 1 2 0 1 0
 1 2 2 2 2 1 2 0 2 1 1 2 0 2 0 0 1 0 1 0 2 0 2 1 1 0 1 0 0 2 2 0 1 1 1 1 2
 2 0 2 0 0 1 1 1 0 2 0 2 1 1 0 1 2 2 1 0 0 1 2 0 1 1 1 1 0 0 0 2 0 1 1 1 2
 2 0 0 1 0 0 2 1 2 1 0 2 2 2 2 0 0 1 2 0 2 1 0 0 2 2 1 2 2 2 0 1 0 0 0 1 2
 0 0 0 0 0 0 1 0 1 0 0 1 2 1 2 1 2 1 0 0 1 0 2 0 1 2 1 2 0 2 2 2 2 0 2 0 2
 2 0 2 0 1 2 0 2 0 2 0 0 1 2 1 0 0 2 1 0 0 0 1 0 2 0 1 2 0 0 0 0 2 0 0 0 2
 2 2 2 2 2 1 1 1 1 0 1 0 1 0 0 2 0 1 2 1 0 1 1 2 1 0 1 0 0 0 0 0 0 1 2 2 0
 0 2 2 1 0 0 0 0 0 1 0 0 1 0 2 2 0 1 1 0 1 0 0 1 1 1 0 1 0 2 1 2 

In [98]:
print(min_sse)

270.64460300255524


In [99]:
print(cluster)

[0 0 0 0 2 2 0 1 2 2 0 0 1 1 0 1 1 2 0 2 1 0 1 2 0 1 1 2 2 2 0 2 0 2 1 1 0
 2 2 2 1 2 2 2 2 1 2 0 1 2 2 2 0 2 0 2 0 1 2 2 2 2 2 2 1 1 1 0 0 1 2 1 2 0
 0 1 2 1 2 0 2 0 0 1 2 1 2 2 2 1 2 1 2 1 2 1 1 0 1 2 2 1 2 0 2 2 1 1 2 0 0
 0 1 0 0 0 2 1 0 1 1 2 0 2 1 1 0 2 0 1 2 1 1 2 0 1 2 1 0 0 2 2 2 0 2 0 0 2
 0 2 2 0 1 2 0 2 0 2 2 2 1 0 0 0 0 2 1 1 0 2 2 2 0 1 1 0 2 1 2 2 1 2 2 1 2
 0 0 0 1 1 1 1 1 0 1 1 0 1 0 2 2 2 0 0 0 1 0 1 1 2 2 0 2 0 2 0 2 0 1 2 0 2
 0 1 1 1 1 0 1 2 1 0 0 1 2 1 2 2 0 2 0 2 1 2 1 0 0 2 0 2 2 1 1 2 0 0 0 0 1
 1 2 1 2 2 0 0 0 2 1 2 1 0 0 2 0 1 1 0 2 2 0 1 2 0 0 0 0 2 2 2 1 2 0 0 0 1
 1 2 2 0 2 2 1 0 1 0 2 1 1 1 1 2 2 0 1 2 1 0 2 2 1 1 0 1 1 1 2 0 2 2 2 0 1
 2 2 2 2 2 2 0 2 0 2 2 0 1 0 1 0 1 0 2 2 0 2 1 2 0 1 0 1 2 1 1 1 1 2 1 2 1
 1 2 1 2 0 1 2 1 2 1 2 2 0 1 0 2 2 1 0 2 2 2 0 2 1 2 0 1 2 2 2 2 1 2 2 2 1
 1 1 1 1 1 0 0 0 0 2 0 2 0 2 2 1 2 0 1 0 2 0 0 1 0 2 0 2 2 0 2 2 2 0 1 1 2
 2 1 1 0 2 2 2 2 2 0 2 2 0 2 1 1 2 0 0 2 0 2 2 0 0 0 2 0 2 1 0 1 0 1 1 1 1
 1 2 0 0 0 2 0 2 0 0 0 0 

# 6 feature

In [100]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('D:/College/Smt 3/Task/Machine Learning/Assignment 8/test.csv')
dataset

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0      0.1        193  ...  16        226      1412  3476    12     7   
1      0.8        191  ...  12        746       857  3895     6     0   
2      0.9        186  ...   4       1270      1366  2396    17    10   
3      0.5         96  ...  20        295      1752  3893    10     0   
4      0.5        108  ...  18        749       810  1773    15     8   
..     ...        ...  ...  ..        ...       ...   ...   ...   ...   
995    0.5        170  ...  17        644       913  2121    14     8   
996    0.9        186  ...   2       1152      1632  1933     8     1   
997    0.5         80  ...  12        477       825  1223     5     0   
998    0.4        171  ...  12         38       832  2509    15    11   
999    0.1        140  ...  19        457       608  2828     9     2   

     talk_time  three_g  touch_screen  wifi  
0            2        0             1     0  
1            7        1             0     0  
2           10        0             1     1  
3            7        1             1     0  
4            7        1             0     1  
..         ...      ...           ...   ...  
995         15        1             1     0  
996         19        0             1     1  
997         14        1             0     0  
998          6        0             1     0  
999          3        1             0     1  

[1000 rows x 21 columns]

In [101]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_selector = SelectKBest(chi2, k=6) 
chi2_selector.fit(X, Y)

cols = chi2_selector.get_support(indices=True)
data_training = X.iloc[:,cols]
data_training.head()

battery_power  int_memory  mobile_wt  px_height  px_width   ram
0            842           7        188         20       756  2549
1           1021          53        136        905      1988  2631
2            563          41        145       1263      1716  2603
3            615          10        131       1216      1786  2769
4           1821          44        141       1208      1212  1411

In [102]:
dataset = dataset.loc[:,['battery_power','int_memory','mobile_wt','px_height','px_width','ram']]
dataset

battery_power  int_memory  mobile_wt  px_height  px_width   ram
0             1043           5        193        226      1412  3476
1              841          61        191        746       857  3895
2             1807          27        186       1270      1366  2396
3             1546          25         96        295      1752  3893
4             1434          49        108        749       810  1773
..             ...         ...        ...        ...       ...   ...
995           1700          54        170        644       913  2121
996            609          13        186       1152      1632  1933
997           1185           8         80        477       825  1223
998           1533          50        171         38       832  2509
999           1270          35        140        457       608  2828

[1000 rows x 6 columns]

In [103]:
from pandas import test
from scipy.sparse import data
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(0,1))
test_data = sc.fit_transform(dataset)
print(test_data)

[[0.36224149 0.0483871  0.94166667 0.11851075 0.60855043 0.86231884]
 [0.22748499 0.9516129  0.925      0.39119035 0.23780895 0.97477187]
 [0.87191461 0.40322581 0.88333333 0.66596749 0.57782231 0.57246377]
 ...
 [0.45697131 0.09677419 0.         0.2501311  0.21643287 0.25764895]
 [0.68912608 0.77419355 0.75833333 0.01992659 0.22110888 0.6027912 ]
 [0.51367578 0.53225806 0.5        0.23964342 0.07147629 0.6884058 ]]


In [104]:
import pandas as pd
from sklearn.cluster import KMeans

max_iterasi = 10
cluster_i = []
cluster_val = [] 
cluster = []

clustering = KMeans(n_clusters=3, init="random", n_init=1)


for i in range(max_iterasi):
    fit =  clustering.fit(test_data)
    clusters = clustering.predict(test_data)
    sse = clustering.inertia_
    print("\nHasil clustering iterasi ke ",i+1,":\n", clusters)
    print("\nSSE iterasi ke ",i+1,":\n", sse)
    print("------------------------------------------------------")
    cluster_i.append(clusters)
    cluster_val.append(sse)

min_sse = min(cluster_val)

index_min = cluster_val.index(min_sse)

cluster = cluster_i[index_min]




Hasil clustering iterasi ke  1 :
 [0 0 2 2 1 0 2 2 1 0 1 0 2 2 0 2 2 0 0 0 2 1 2 1 2 2 1 1 0 1 2 0 2 0 2 2 2
 1 0 1 2 0 1 0 0 1 1 2 2 1 1 1 2 1 2 0 2 2 0 1 1 0 1 0 0 1 2 2 0 2 0 2 0 2
 2 0 1 2 0 0 1 2 2 0 0 2 0 0 1 1 1 1 0 2 0 1 2 0 1 1 1 2 1 2 1 0 2 1 1 0 0
 0 1 1 2 0 1 2 2 0 1 0 1 1 2 2 2 1 0 2 1 2 0 0 2 2 0 2 1 0 1 0 0 2 0 2 2 1
 2 1 0 2 2 0 0 1 2 1 1 1 1 0 1 2 2 1 1 2 2 0 1 1 2 2 2 2 1 2 1 1 2 0 1 2 0
 0 2 2 2 0 2 2 2 2 2 1 0 1 2 1 1 1 0 0 0 2 0 2 1 0 1 2 1 2 0 2 1 1 0 1 0 0
 2 2 2 2 2 0 2 1 2 0 0 2 1 2 0 1 1 1 2 0 2 1 0 2 2 1 0 1 1 0 0 0 0 0 2 2 1
 2 1 1 1 1 2 0 2 1 2 1 1 0 2 0 0 2 2 2 0 1 0 2 0 2 2 0 1 0 0 1 2 0 0 0 2 2
 2 1 0 0 1 1 2 2 2 2 0 0 2 2 2 0 1 2 2 0 2 2 0 1 1 2 1 2 2 2 1 0 1 1 0 2 2
 0 1 1 1 1 0 2 0 0 1 0 2 2 0 0 0 1 2 1 0 0 1 2 0 0 2 2 2 1 2 1 0 2 1 1 1 2
 2 1 2 1 0 1 1 1 1 2 0 0 2 1 0 0 1 2 2 0 1 1 0 0 2 1 0 2 0 1 1 0 2 1 1 1 2
 2 1 1 2 2 1 0 1 2 0 0 0 0 1 0 2 1 1 2 2 1 2 2 1 2 0 0 1 0 0 1 1 1 1 1 1 0
 0 2 2 0 1 1 1 0 0 1 0 0 1 1 2 2 0 2 0 0 0 0 1 2 0 2 1 2 1 1 2 2 

In [105]:
print(min_sse)

356.41130064200695


In [106]:
print(cluster)

[1 1 0 0 2 1 0 0 2 1 2 1 0 0 1 0 0 1 1 1 0 2 0 2 0 0 2 2 1 2 0 1 0 1 0 0 0
 2 1 2 0 1 2 1 1 2 2 0 0 1 2 2 0 1 0 1 0 0 1 2 2 1 2 1 1 2 0 0 1 0 1 0 1 0
 0 1 2 0 1 1 2 0 0 1 1 0 1 1 2 2 2 2 1 0 1 2 0 1 2 2 2 0 2 0 2 1 0 2 2 1 1
 1 2 1 0 1 2 0 0 1 2 1 2 2 0 0 2 2 1 0 2 0 1 1 0 2 1 0 2 0 2 1 1 0 1 0 0 2
 0 2 1 0 0 1 1 2 0 2 2 2 2 1 2 0 0 2 2 2 0 1 2 2 0 0 2 0 2 0 2 2 0 1 2 0 1
 0 0 0 0 1 0 0 0 0 2 2 0 2 0 2 2 2 1 1 1 0 0 0 2 1 2 0 2 0 1 0 2 2 1 2 2 1
 0 0 1 0 0 1 0 2 2 1 1 0 2 0 1 2 2 2 0 1 0 2 1 0 0 2 0 2 2 1 1 1 1 1 0 0 2
 0 2 2 2 2 0 1 0 2 0 2 2 0 0 1 1 0 0 0 1 2 1 0 1 0 0 1 2 1 1 2 0 1 1 1 0 0
 0 2 1 1 1 1 0 0 0 0 1 1 0 0 0 1 2 0 0 1 0 0 1 2 2 0 2 0 0 0 2 1 2 2 1 0 0
 1 2 2 2 2 1 0 1 1 2 1 0 0 1 1 1 2 0 2 1 1 2 0 1 0 0 0 0 2 0 2 1 0 2 2 2 0
 0 2 0 2 1 2 2 2 2 0 1 1 0 2 1 1 2 0 0 1 2 2 1 1 0 2 1 0 1 2 2 1 0 2 1 2 0
 0 2 2 0 0 2 0 2 0 1 1 1 1 2 1 0 2 2 0 0 2 0 0 2 0 1 1 2 1 1 2 2 2 2 2 2 1
 1 0 0 1 2 2 2 1 1 2 1 1 2 2 0 0 1 0 1 1 1 1 1 0 0 0 2 0 2 2 0 0 0 0 0 0 2
 0 2 1 0 0 1 0 1 0 0 0 0 

# 7 feature

In [107]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('D:/College/Smt 3/Task/Machine Learning/Assignment 8/test.csv')
dataset

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0      0.1        193  ...  16        226      1412  3476    12     7   
1      0.8        191  ...  12        746       857  3895     6     0   
2      0.9        186  ...   4       1270      1366  2396    17    10   
3      0.5         96  ...  20        295      1752  3893    10     0   
4      0.5        108  ...  18        749       810  1773    15     8   
..     ...        ...  ...  ..        ...       ...   ...   ...   ...   
995    0.5        170  ...  17        644       913  2121    14     8   
996    0.9        186  ...   2       1152      1632  1933     8     1   
997    0.5         80  ...  12        477       825  1223     5     0   
998    0.4        171  ...  12         38       832  2509    15    11   
999    0.1        140  ...  19        457       608  2828     9     2   

     talk_time  three_g  touch_screen  wifi  
0            2        0             1     0  
1            7        1             0     0  
2           10        0             1     1  
3            7        1             1     0  
4            7        1             0     1  
..         ...      ...           ...   ...  
995         15        1             1     0  
996         19        0             1     1  
997         14        1             0     0  
998          6        0             1     0  
999          3        1             0     1  

[1000 rows x 21 columns]

In [108]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_selector = SelectKBest(chi2, k=7) 
chi2_selector.fit(X, Y)

cols = chi2_selector.get_support(indices=True)
data_training = X.iloc[:,cols]
data_training.head()

battery_power  int_memory  mobile_wt  px_height  px_width   ram  sc_w
0            842           7        188         20       756  2549     7
1           1021          53        136        905      1988  2631     3
2            563          41        145       1263      1716  2603     2
3            615          10        131       1216      1786  2769     8
4           1821          44        141       1208      1212  1411     2

In [109]:
dataset = dataset.loc[:,['battery_power','int_memory','mobile_wt','px_height','px_width','ram','sc_w']]
dataset

battery_power  int_memory  mobile_wt  px_height  px_width   ram  sc_w
0             1043           5        193        226      1412  3476     7
1              841          61        191        746       857  3895     0
2             1807          27        186       1270      1366  2396    10
3             1546          25         96        295      1752  3893     0
4             1434          49        108        749       810  1773     8
..             ...         ...        ...        ...       ...   ...   ...
995           1700          54        170        644       913  2121     8
996            609          13        186       1152      1632  1933     1
997           1185           8         80        477       825  1223     0
998           1533          50        171         38       832  2509    11
999           1270          35        140        457       608  2828     2

[1000 rows x 7 columns]

In [110]:
from pandas import test
from scipy.sparse import data
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(0,1))
test_data = sc.fit_transform(dataset)
print(test_data)

[[0.36224149 0.0483871  0.94166667 ... 0.60855043 0.86231884 0.38888889]
 [0.22748499 0.9516129  0.925      ... 0.23780895 0.97477187 0.        ]
 [0.87191461 0.40322581 0.88333333 ... 0.57782231 0.57246377 0.55555556]
 ...
 [0.45697131 0.09677419 0.         ... 0.21643287 0.25764895 0.        ]
 [0.68912608 0.77419355 0.75833333 ... 0.22110888 0.6027912  0.61111111]
 [0.51367578 0.53225806 0.5        ... 0.07147629 0.6884058  0.11111111]]


In [111]:
import pandas as pd
from sklearn.cluster import KMeans

max_iterasi = 10
cluster_i = []
cluster_val = [] 
cluster = []

clustering = KMeans(n_clusters=3, init="random", n_init=1)


for i in range(max_iterasi):
    fit =  clustering.fit(test_data)
    clusters = clustering.predict(test_data)
    sse = clustering.inertia_
    print("\nHasil clustering iterasi ke ",i+1,":\n", clusters)
    print("\nSSE iterasi ke ",i+1,":\n", sse)
    print("------------------------------------------------------")
    cluster_i.append(clusters)
    cluster_val.append(sse)

min_sse = min(cluster_val)

index_min = cluster_val.index(min_sse)

cluster = cluster_i[index_min]



Hasil clustering iterasi ke  1 :
 [0 2 1 0 2 2 1 1 0 0 2 1 1 1 1 1 1 2 1 2 0 1 1 2 0 1 0 0 0 2 0 2 1 2 1 1 0
 0 2 0 1 2 0 0 2 2 0 1 1 0 2 2 1 2 1 0 1 0 0 0 0 2 2 2 0 2 1 0 2 1 2 1 2 1
 1 2 0 1 0 1 2 1 1 2 0 1 2 2 2 0 2 1 0 1 2 0 1 0 2 0 0 1 0 1 2 2 1 2 2 2 2
 1 2 2 0 2 0 1 0 1 0 2 2 2 1 1 0 0 1 1 0 1 0 2 1 0 2 1 1 1 2 2 2 1 0 1 1 2
 1 2 0 1 0 2 1 0 1 2 0 0 1 2 0 1 1 2 2 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 2
 1 1 1 1 2 1 1 1 1 0 2 0 0 0 2 2 2 1 2 1 1 0 1 0 0 2 1 2 1 2 1 2 0 0 0 0 2
 1 0 2 0 1 2 1 2 1 2 2 1 2 1 0 2 0 0 1 2 1 0 2 0 1 2 1 2 2 1 1 0 1 2 1 1 2
 0 0 0 2 2 1 0 0 2 0 2 0 1 0 0 2 0 1 0 0 2 1 1 2 0 1 1 2 2 2 2 1 2 1 0 1 0
 0 2 0 1 0 2 1 1 1 1 2 1 1 1 0 2 0 1 1 2 1 1 2 0 2 1 2 1 1 1 0 2 0 0 2 1 1
 2 2 2 0 2 0 1 0 2 2 0 1 1 1 0 1 2 1 0 0 1 0 1 2 1 0 1 1 0 1 0 1 2 2 2 2 1
 0 2 1 2 1 1 0 0 2 1 2 2 1 1 1 2 0 1 1 0 0 2 1 2 2 0 1 1 2 0 2 2 1 2 2 0 0
 1 0 2 1 1 0 0 2 1 2 0 2 2 0 0 1 0 2 1 1 2 1 1 2 1 2 1 2 0 2 0 2 2 2 0 1 2
 0 1 0 1 2 2 2 2 0 2 2 2 0 0 1 1 0 1 1 2 1 2 2 1 1 1 0 1 2 1 1 1 

In [112]:
print(min_sse)

411.0507047645738


In [113]:
print(cluster)

[1 0 1 1 0 0 1 2 0 0 1 1 2 2 1 2 2 0 1 0 2 1 2 0 1 2 2 0 0 0 1 0 1 0 2 2 1
 0 0 0 2 0 0 0 0 2 0 1 2 0 0 0 1 0 1 0 1 2 0 0 0 0 0 0 2 2 2 1 1 2 0 2 0 1
 1 2 0 2 0 1 0 1 1 2 0 2 0 0 0 2 0 2 0 2 0 2 2 1 2 0 0 2 0 1 0 0 2 2 0 1 1
 1 2 1 1 1 0 2 1 2 2 0 0 0 2 2 1 0 1 2 0 2 2 0 1 2 0 2 1 1 0 0 0 1 0 1 1 0
 1 0 0 1 2 0 1 0 1 0 0 0 2 1 1 1 1 0 2 2 1 0 0 0 1 2 2 1 0 2 0 0 2 0 0 2 0
 1 1 1 2 2 2 2 2 1 2 2 1 2 1 0 0 0 1 1 1 2 1 2 2 0 0 1 0 1 0 1 0 1 2 0 1 0
 1 2 2 2 2 0 2 0 2 0 1 2 0 2 0 0 1 0 1 0 2 0 2 1 1 0 1 0 0 2 2 0 1 1 1 1 2
 2 0 2 0 0 1 1 1 0 2 0 2 1 1 0 1 2 2 1 0 0 1 2 0 1 1 1 1 0 0 0 2 0 1 1 1 2
 2 0 0 1 0 0 2 1 2 1 0 2 2 2 2 0 0 1 2 0 2 1 0 0 2 2 1 1 2 2 0 0 0 0 0 1 2
 0 0 0 0 0 0 1 0 0 0 0 1 2 1 2 1 2 1 0 0 1 0 1 0 1 2 1 2 0 2 2 2 2 0 2 0 2
 2 0 2 0 1 2 0 2 0 2 0 0 1 2 1 0 0 2 1 0 0 0 1 0 2 0 1 2 0 0 0 0 2 0 0 0 2
 2 2 2 2 2 1 1 0 1 0 1 0 1 0 0 2 0 0 2 1 0 1 1 2 1 0 1 0 0 1 0 0 0 1 2 2 0
 0 2 2 1 0 0 0 0 0 1 0 0 1 0 2 2 0 1 1 0 1 0 0 1 1 1 0 1 0 2 1 2 1 2 2 2 2
 2 0 1 1 1 0 1 0 1 1 1 1 